root: true
extends: remcohaszing
rules:
  '@typescript-eslint/no-invalid-void-type': off
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/no-redeclare': off
  import/no-extraneous-dependencies: off
