[build]
publish = 'example/dist/'
command = 'npm run prepack && npx vite build example'

[[headers]]
  for = '/*'
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'"
