[build]
publish = 'build/'
command = 'npx vite build'

[[headers]]
  for = '/*'
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src *; img-src 'self' data:; style-src 'self' 'unsafe-inline'"
